import argparse
import json
import shutil
from dataclasses import dataclass, replace
from pathlib import Path

import brian2 as b2
import matplotlib.pyplot as plt
import numpy as np

from stimulus import StimulusParams, hydrodynamic_velocity_parallel, simulate_lateral_line

# Keep codegen simple/portable.
b2.prefs.codegen.target = "numpy"


@dataclass
class NetworkParams:
    # -----------------------------
    # Network sizes (as requested)
    # -----------------------------
    n_ll: int = 100
    n_mon: int = 3200
    n_ts: int = 300

    # -----------------------------
    # Time setup
    # -----------------------------
    dt_s: float = 0.001
    trial_duration_s: float = 1.2
    n_training_trials: int = 200
    checkpoint_trials: int = 10
    pv_eval_every_checkpoints: int = 2

    # During training, one random snapshot is held for this duration.
    training_position_hold_s: float = 0.05
    # Training noise curriculum: set both to 0 for deterministic training.
    # Example: early=0.0, late=1.0 to add noise in later training.
    training_noise_scale_early: float = 0.0
    training_noise_scale_late: float = 0.0
    training_noise_switch_fraction: float = 0.5
    # Structured training for clearer map emergence.
    training_ordered_sweeps: bool = True
    training_fixed_distance: bool = True
    training_bidirectional: bool = False
    # Restrict training to near-field distances where LL SNR is acceptable.
    training_distance_min_cm: float = 0.8
    training_distance_max_cm: float = 1.8

    # -----------------------------
    # Stimulus setup
    # -----------------------------
    speed_cm_s: float = 5.0
    distance_cm: float = 1.5
    direction: float = 1.0
    # Use raw LL firing rates or only modulation above spontaneous baseline.
    # "raw":    rLL as generated by the hydrodynamic model
    # "modulation": max(rLL - r0, 0), biologically akin to baseline cancellation
    ll_rate_mode: str = "raw"
    # Additional baseline subtraction and gain on LL rates (applied before PoissonGroup).
    ll_rate_baseline_subtract_hz: float = 0.0
    ll_rate_gain: float = 1.0

    # Test path exactly 4 cm.
    test_path_cm: float = 4.0

    seed: int = 123

    # -----------------------------
    # LIF constants (requested)
    # -----------------------------
    vth_mV: float = -54.0
    vreset_mV: float = -60.0
    el_mV: float = -74.0
    tau_ref_ms: float = 2.0
    tau_m_ms: float = 10.0
    tau_s_ms: float = 2.0

    # -----------------------------
    # Connectivity structure
    # -----------------------------
    # LL -> MON: random sparse projection with optional weak somatotopy.
    p_ll_to_mon: float = 0.03
    ll_to_mon_in_degree: int = 3
    ll_to_mon_sigma: float = 15.0
    ll_to_mon_topography_strength: float = 0.01
    ll_mon_w_mean_mV: float = 7.0
    ll_mon_w_jitter_mV: float = 3.0

    # Optional LL -> MON STDP (plastic expansion layer, tuned from design script).
    ll_mon_use_stdp: bool = False
    ll_mon_apre: float = 0.01
    ll_mon_apost: float = -0.0105
    ll_mon_wmax_mV: float = 20.0
    ll_mon_w_init_mV: float = 10.0
    ll_mon_w_jitter_stdp_mV: float = 2.0
    # Homeostatic normalization of incoming LL->MON weights (per MON neuron).
    ll_mon_homeo_eta: float = 0.02
    ll_mon_homeo_every_trials: int = 10

    # MON -> TS: random + weak somatotopy (distillation stage in space).
    mon_to_ts_out_degree: int = 16
    mon_to_ts_sigma: float = 120.0
    mon_to_ts_topography_strength: float = 0.05

    # -----------------------------
    # STDP on MON -> TS ONLY
    # Table III values.
    # -----------------------------
    mon_ts_apre: float = 0.02
    mon_ts_apost: float = -0.021
    mon_ts_wmax: float = 0.045
    mon_ts_w_init: float = 0.020
    mon_ts_w_jitter: float = 0.010

    # Scale from dimensionless weight to PSP size in mV.
    mon_ts_gain_mV: float = 30.0

    # -----------------------------
    # Inhibition / noisy background
    # -----------------------------
    # Global inhibition in MON for gain control / sparsity.
    mon_to_global_inh_p: float = 0.06
    mon_to_global_inh_drive_mV: float = 0.5
    global_inh_to_mon_mV: float = 1.4

    # TS local lateral inhibition for map sharpening.
    ts_lateral_radius: int = 14
    ts_local_inh_peak_mV: float = 1.0

    # Optional TS activity-dependent feedback inhibition (global TS inhibition).
    use_ts_feedback_inh: bool = False
    ts_to_global_inh_p: float = 0.12
    ts_to_global_inh_drive_mV: float = 0.35
    global_inh_to_ts_mV: float = 0.8

    # Background poisson drive.
    bg_rate_mon_hz: float = 22.0
    bg_rate_ts_hz: float = 12.0
    bg_w_mon_mV: float = 1.5
    bg_w_ts_mV: float = 0.60


def apply_model_mode(params: NetworkParams, mode: str) -> NetworkParams:
    """
    Apply named parameter presets.

    Modes:
      - ll_thesis: strict lateral-line setting from thesis context.
      - ll_fast: reduced sizes for quick checks.
    """
    mode = mode.strip().lower()

    if mode == "ll_thesis":
        return replace(
            params,
            # Lateral-line architecture from thesis context.
            n_ll=100,
            n_mon=3200,
            n_ts=300,
            # Long training with fixed network dynamics.
            n_training_trials=1000,
            trial_duration_s=1.2,
            checkpoint_trials=5,
            # Gentler MON->TS STDP so map does not collapse to edge attractors.
            mon_ts_apre=0.008,
            mon_ts_apost=-0.0084,
            mon_ts_wmax=0.028,
            mon_ts_w_init=0.020,
            mon_ts_w_jitter=0.005,
            # Slightly lower feedforward drive to keep TS sparse.
            ll_mon_w_mean_mV=11.5,
            # Very weak somatotopy in both expansion and distillation projections.
            ll_to_mon_in_degree=10,
            # Bootstrap learning with stronger anatomical correlation.
            ll_to_mon_topography_strength=0.08,
            mon_to_ts_topography_strength=0.08,
            mon_to_ts_out_degree=16,
            mon_to_ts_sigma=140.0,
            mon_ts_gain_mV=72.0,
            mon_to_global_inh_p=0.03,
            global_inh_to_mon_mV=1.15,
            ts_lateral_radius=18,
            ts_local_inh_peak_mV=1.4,
            use_ts_feedback_inh=True,
            ts_to_global_inh_p=0.08,
            ts_to_global_inh_drive_mV=0.25,
            global_inh_to_ts_mV=0.35,
            bg_rate_mon_hz=22.0,
            bg_rate_ts_hz=10.0,
            bg_w_ts_mV=0.75,
            # Start with no training noise to verify map mechanism.
            training_noise_scale_early=0.0,
            training_noise_scale_late=0.0,
            training_bidirectional=False,
            # Train in a near-field distance band for better SNR.
            training_fixed_distance=False,
            training_distance_min_cm=0.8,
            training_distance_max_cm=1.8,
            # Thesis-consistent stimulus speed.
            speed_cm_s=5.0,
            test_path_cm=5.0,
        )

    if mode == "ll_fast":
        return replace(
            params,
            n_mon=800,
            n_ts=80,
            n_training_trials=40,
            trial_duration_s=0.8,
            checkpoint_trials=10,
        )

    raise ValueError(f"Unknown mode '{mode}'. Use 'll_thesis' or 'll_fast'.")


# ---------------------------------------------------------
# Connectivity helpers
# ---------------------------------------------------------
def build_mon_to_ts_indices(
    n_mon: int,
    n_ts: int,
    out_degree: int,
    sigma_ts: float,
    topography_strength: float,
    seed: int,
):
    """
    Build MON->TS indices with mixed random + weak topographic targets.

    topography_strength:
      0.0 -> fully random
      1.0 -> fully weak-somatotopic
    """
    rng = np.random.default_rng(seed)
    mon_pos = np.linspace(0.0, 1.0, n_mon)
    i_list: list[int] = []
    j_list: list[int] = []

    topo_strength = float(np.clip(topography_strength, 0.0, 1.0))

    for mon_idx in range(n_mon):
        n_topo = int(round(out_degree * topo_strength))
        n_rand = out_degree - n_topo

        parts: list[np.ndarray] = []

        # Topographic part.
        if n_topo > 0:
            if sigma_ts >= n_ts:
                topo_targets = rng.integers(0, n_ts, size=n_topo)
            else:
                center = mon_pos[mon_idx] * (n_ts - 1)
                topo_targets = np.rint(rng.normal(center, sigma_ts, size=n_topo)).astype(int)
                topo_targets = np.clip(topo_targets, 0, n_ts - 1)
            parts.append(topo_targets)

        # Random part.
        if n_rand > 0:
            parts.append(rng.integers(0, n_ts, size=n_rand))

        targets = np.concatenate(parts)
        rng.shuffle(targets)

        i_list.extend([mon_idx] * out_degree)
        j_list.extend(targets.tolist())

    return np.asarray(i_list), np.asarray(j_list), mon_pos


def build_ll_to_mon_indices(
    n_ll: int,
    n_mon: int,
    in_degree: int,
    sigma_ll: float,
    topography_strength: float,
    seed: int,
):
    """
    Build LL->MON indices with mixed random + weak topographic sources.

    topography_strength:
      0.0 -> fully random
      1.0 -> fully weak-somatotopic
    """
    rng = np.random.default_rng(seed)
    mon_pos = np.linspace(0.0, 1.0, n_mon)
    i_list: list[int] = []
    j_list: list[int] = []

    topo_strength = float(np.clip(topography_strength, 0.0, 1.0))

    for mon_idx in range(n_mon):
        n_topo = int(round(in_degree * topo_strength))
        n_rand = in_degree - n_topo
        parts: list[np.ndarray] = []

        if n_topo > 0:
            if sigma_ll >= n_ll:
                topo_sources = rng.integers(0, n_ll, size=n_topo)
            else:
                center = mon_pos[mon_idx] * (n_ll - 1)
                topo_sources = np.rint(rng.normal(center, sigma_ll, size=n_topo)).astype(int)
                topo_sources = np.clip(topo_sources, 0, n_ll - 1)
            parts.append(topo_sources)

        if n_rand > 0:
            parts.append(rng.integers(0, n_ll, size=n_rand))

        sources = np.concatenate(parts)
        rng.shuffle(sources)
        i_list.extend(sources.tolist())
        j_list.extend([mon_idx] * in_degree)

    return np.asarray(i_list), np.asarray(j_list)


# ---------------------------------------------------------
# Stimulus helpers
# ---------------------------------------------------------
def _build_spatial_noise_cholesky(xi_cm: np.ndarray, stim_params: StimulusParams):
    """Spatial correlation for LL noise."""
    dist = xi_cm[:, None] - xi_cm[None, :]
    corr = np.exp(-0.5 * (dist / stim_params.l_noise_cm) ** 2)
    return np.linalg.cholesky(corr + 1e-12 * np.eye(xi_cm.size))


def _sample_instantaneous_rates(
    rng: np.random.Generator,
    params: NetworkParams,
    stim_params: StimulusParams,
    xi_cm: np.ndarray,
    yi_cm: np.ndarray,
    noise_chol: np.ndarray,
    x_cm: float | None = None,
    noise_scale: float = 1.0,
    fixed_distance_cm: float | None = None,
    fixed_direction: float | None = None,
    distance_min_cm: float | None = None,
    distance_max_cm: float | None = None,
):
    """One random hydrodynamic snapshot -> LL rates."""
    if fixed_distance_cm is None:
        d_cm = float(rng.normal(stim_params.mu_distance_cm, stim_params.sigma_distance_cm))
    else:
        d_cm = float(fixed_distance_cm)
    if distance_min_cm is not None:
        d_cm = max(float(distance_min_cm), d_cm)
    if distance_max_cm is not None:
        d_cm = min(float(distance_max_cm), d_cm)
    if fixed_direction is None:
        direction = 1.0 if rng.random() < 0.5 else -1.0
    else:
        direction = float(np.sign(fixed_direction)) if fixed_direction != 0 else 1.0
    if x_cm is None:
        x_cm = float(rng.uniform(-1.0, stim_params.lateral_line_length_cm + 1.0))
    else:
        x_cm = float(x_cm)

    v = hydrodynamic_velocity_parallel(
        xi_cm,
        yi_cm,
        X_cm=x_cm,
        Y_cm=d_cm,
        U_cm_s=params.speed_cm_s,
        R_cm=stim_params.sphere_radius_cm,
        eX=direction,
        eY=0.0,
        sx=1.0,
        sy=0.0,
    )

    eta = (noise_scale * stim_params.sigma_noise_hz) * (noise_chol @ rng.standard_normal(params.n_ll))
    rates = np.clip(stim_params.r0_hz + stim_params.A_per_cm * v + eta, 0.0, stim_params.rmax_hz)
    return rates, {"X_cm": x_cm, "D_cm": d_cm, "direction": direction}


def make_training_rates(params: NetworkParams):
    """Balanced-position snapshot training stream for all training trials."""
    rng = np.random.default_rng(params.seed)
    stim_params = StimulusParams()

    xi_cm = np.linspace(0.0, stim_params.lateral_line_length_cm, params.n_ll)
    yi_cm = np.zeros_like(xi_cm)
    noise_chol = _build_spatial_noise_cholesky(xi_cm, stim_params)

    total_train_s = params.n_training_trials * params.trial_duration_s
    n_steps = int(np.round(total_train_s / params.dt_s))
    hold_steps = max(1, int(np.round(params.training_position_hold_s / params.dt_s)))

    rates = np.zeros((n_steps, params.n_ll), dtype=float)
    x_trace_cm = np.zeros(n_steps, dtype=float)
    samples = []

    # Balanced x sampling across the full 4 cm lateral line.
    x_bins = np.linspace(0.0, stim_params.lateral_line_length_cm, params.n_ll)
    x_seq = []
    if params.training_ordered_sweeps:
        # Deterministic forward/backward sweeps reduce ambiguity and improve map learning.
        while len(x_seq) * hold_steps < n_steps:
            x_seq.extend(x_bins.tolist())
            x_seq.extend(x_bins[::-1].tolist())
    else:
        while len(x_seq) * hold_steps < n_steps:
            xb = x_bins.copy()
            rng.shuffle(xb)
            x_seq.extend(xb.tolist())

    idx = 0
    k = 0
    while idx < n_steps:
        frac = idx / max(1, n_steps - 1)
        noise_scale = (
            params.training_noise_scale_early
            if frac < params.training_noise_switch_fraction
            else params.training_noise_scale_late
        )
        inst_rates, meta = _sample_instantaneous_rates(
            rng,
            params,
            stim_params,
            xi_cm,
            yi_cm,
            noise_chol,
            x_cm=x_seq[k],
            noise_scale=noise_scale,
            fixed_distance_cm=(stim_params.mu_distance_cm if params.training_fixed_distance else None),
            fixed_direction=(1.0 if (params.training_bidirectional is False or (k % 2 == 0)) else -1.0),
            distance_min_cm=params.training_distance_min_cm,
            distance_max_cm=params.training_distance_max_cm,
        )
        nxt = min(n_steps, idx + hold_steps)
        rates[idx:nxt, :] = inst_rates[None, :]
        x_trace_cm[idx:nxt] = x_seq[k]
        meta["t_start_s"] = idx * params.dt_s
        meta["t_end_s"] = nxt * params.dt_s
        samples.append(meta)
        idx = nxt
        k += 1

    return rates, samples, x_trace_cm


def make_test_rates(params: NetworkParams):
    """Continuous moving-sphere test sweep.

    For the lateral line (0..4 cm), we sometimes want the sphere center to
    traverse a longer path (e.g. -0.5..4.5 cm) so the endpoints are not
    over-emphasized by geometry.
    """
    test_duration_s = params.test_path_cm / max(params.speed_cm_s, 1e-9)
    # Place the sphere center so that a 5 cm path covers [-0.5, 4.5] when direction=+1.
    # For any path length, we start at x = -0.5 and move forward; LL neuromasts still span 0..4 cm.
    stim_params = StimulusParams()
    x0_cm = -0.5 if params.direction >= 0 else (stim_params.lateral_line_length_cm + 0.5)
    sim = simulate_lateral_line(
        duration_s=test_duration_s,
        dt_s=params.dt_s,
        n_neuromasts=params.n_ll,
        seed=params.seed + 999,
        fixed_distance_cm=params.distance_cm,
        direction=params.direction,
        fixed_speed_cm_s=params.speed_cm_s,
        x0_cm=x0_cm,
        params=stim_params,
    )
    return sim


# ---------------------------------------------------------
# Map metric + stabilization metric
# ---------------------------------------------------------
def _wrap_to_pi(x: np.ndarray) -> np.ndarray:
    return (x + np.pi) % (2.0 * np.pi) - np.pi


def _circ_mean(x: np.ndarray) -> float:
    if x.size == 0:
        return np.nan
    return float(np.arctan2(np.mean(np.sin(x)), np.mean(np.cos(x))))


def _circ_std(x: np.ndarray) -> float:
    if x.size == 0:
        return np.nan
    c = np.mean(np.cos(x))
    s = np.mean(np.sin(x))
    r = np.sqrt(c * c + s * s)
    r = float(np.clip(r, 1e-12, 1.0))
    return float(np.sqrt(-2.0 * np.log(r)))


def pv_map_quality_from_ts_spikes(
    ts_spike_t_s: np.ndarray,
    ts_spike_i: np.ndarray,
    n_ts: int,
    test_t_s: np.ndarray,
    test_x_cm: np.ndarray,
    lateral_line_len_cm: float,
    test_start_s: float,
    dt_s: float,
    n_pos_bins: int = 100,
):
    """
    Population-vector map quality following thesis §4.1.4 ideas:
    - theta_hat(t) from PV direction
    - delta_theta(t) = theta_hat - theta_true (wrapped)
    - bias(theta0), trial variability sigma_trial(theta0)
    - somatotopic error sigma_theta = dispersion of bias over theta0
    """
    n_t = test_t_s.size
    rates = np.zeros((n_t, n_ts), dtype=float)

    # Bin TS spikes into test-time bins.
    t_rel = ts_spike_t_s - test_start_s
    k = np.floor(t_rel / dt_s).astype(int)
    valid = (k >= 0) & (k < n_t) & (ts_spike_i >= 0) & (ts_spike_i < n_ts)
    if np.any(valid):
        np.add.at(rates, (k[valid], ts_spike_i[valid]), 1.0 / dt_s)

    # Temporal smoothing improves PV robustness when activity is sparse in single ms bins.
    smooth_win = max(1, int(round(0.02 / max(dt_s, 1e-9))))  # ~20 ms
    if smooth_win > 1:
        kernel = np.ones(smooth_win, dtype=float) / float(smooth_win)
        rates = np.apply_along_axis(lambda v: np.convolve(v, kernel, mode="same"), 0, rates)

    # Preferred directions for TS neurons on [0, 2pi).
    phi = 2.0 * np.pi * np.arange(n_ts, dtype=float) / float(n_ts)
    ejphi = np.exp(1j * phi)
    denom = np.sum(rates, axis=1)
    z = np.zeros(n_t, dtype=np.complex128)
    nz = denom > 1e-12
    if np.any(nz):
        z[nz] = (rates[nz] @ ejphi) / denom[nz]

    theta_hat = np.zeros(n_t, dtype=float)
    theta_hat[nz] = np.mod(np.angle(z[nz]), 2.0 * np.pi)
    theta_hat[~nz] = np.nan

    # True position mapped to angle.
    x_clip = np.clip(test_x_cm, 0.0, lateral_line_len_cm)
    theta_true = 2.0 * np.pi * x_clip / lateral_line_len_cm

    # Estimation error.
    delta = np.full(n_t, np.nan, dtype=float)
    m = np.isfinite(theta_hat)
    delta[m] = _wrap_to_pi(theta_hat[m] - theta_true[m])

    # Position-dependent bias and trial variability.
    edges = np.linspace(0.0, 2.0 * np.pi, n_pos_bins + 1)
    centers = 0.5 * (edges[:-1] + edges[1:])
    bias = np.full(n_pos_bins, np.nan, dtype=float)
    sigma_trial = np.full(n_pos_bins, np.nan, dtype=float)
    for b in range(n_pos_bins):
        mb = m & (theta_true >= edges[b]) & (theta_true < edges[b + 1])
        eb = delta[mb]
        if eb.size >= 1:
            mu = _circ_mean(eb)
            bias[b] = mu
            sigma_trial[b] = _circ_std(_wrap_to_pi(eb - mu)) if eb.size >= 2 else 0.0

    vb = np.isfinite(bias)
    vd = np.isfinite(delta)
    sigma_theta = _circ_std(bias[vb]) if np.any(vb) else (_circ_std(delta[vd]) if np.any(vd) else np.pi)
    delta_trial = (
        float(np.sqrt(np.nanmean(sigma_trial**2)))
        if np.any(np.isfinite(sigma_trial))
        else (_circ_std(delta[vd]) if np.any(vd) else np.pi)
    )
    valid_fraction = float(np.mean(vd)) if vd.size > 0 else 0.0

    return {
        "theta_true": theta_true,
        "theta_hat": theta_hat,
        "delta_theta": delta,
        "theta_bins": centers,
        "bias_theta": bias,
        "sigma_trial_theta": sigma_trial,
        "sigma_theta": sigma_theta,
        "delta_trial": delta_trial,
        "valid_fraction": valid_fraction,
    }


def estimate_stabilization_time(epoch_t_s: np.ndarray, w_mean_series: np.ndarray):
    """When mean MON->TS weight changes by <1% for 4 consecutive checkpoints."""
    if epoch_t_s.size < 6:
        return None

    dw = np.abs(np.diff(w_mean_series))
    ref = max(float(np.abs(w_mean_series[-1])), 1e-12)
    rel_dw = dw / ref

    # Use a stricter 0.5% threshold so 'stabilized' really means very slow change.
    threshold = 0.005
    window = 4
    for i in range(window - 1, rel_dw.size):
        if np.all(rel_dw[i - window + 1 : i + 1] < threshold):
            return float(epoch_t_s[i + 1])
    return None


# ---------------------------------------------------------
# Single-training pipeline (no temporal phase split)
# ---------------------------------------------------------
def run_spatial_two_stage_model(params: NetworkParams):
    # Build training and test stimuli.
    train_rates, train_samples, train_x_cm = make_training_rates(params)
    test_sim = make_test_rates(params)
    test_rates = test_sim["rates_hz"]

    # Concatenate training + test in one TimedArray.
    rates_all = np.vstack([train_rates, test_rates])
    baseline_subtract_hz = float(max(0.0, params.ll_rate_baseline_subtract_hz))
    if params.ll_rate_mode == "modulation":
        baseline_subtract_hz += float(StimulusParams().r0_hz)
    elif params.ll_rate_mode != "raw":
        raise ValueError(f"Unknown ll_rate_mode '{params.ll_rate_mode}'. Use 'raw' or 'modulation'.")
    rates_all = np.clip((rates_all - baseline_subtract_hz) * float(max(0.0, params.ll_rate_gain)), 0.0, None)

    train_duration_s = params.n_training_trials * params.trial_duration_s
    test_duration_s = float(test_sim["t_s"][-1] + params.dt_s)
    total_duration_s = train_duration_s + test_duration_s

    b2.start_scope()
    b2.defaultclock.dt = params.dt_s * b2.second

    all_rates_ta = b2.TimedArray(rates_all * b2.Hz, dt=params.dt_s * b2.second)
    ll = b2.PoissonGroup(params.n_ll, rates="all_rates_ta(t, i)", namespace={"all_rates_ta": all_rates_ta})

    # LIF equations.
    eqs = """
    dv/dt = (El - v + ge - gi) / tau_m : volt (unless refractory)
    dge/dt = -ge / tau_s : volt
    dgi/dt = -gi / tau_s : volt
    """
    ns = {
        "Vth": params.vth_mV * b2.mV,
        "Vreset": params.vreset_mV * b2.mV,
        "El": params.el_mV * b2.mV,
        "tau_ref": params.tau_ref_ms * b2.ms,
        "tau_m": params.tau_m_ms * b2.ms,
        "tau_s": params.tau_s_ms * b2.ms,
    }

    mon = b2.NeuronGroup(params.n_mon, eqs, threshold="v > Vth", reset="v = Vreset", refractory="tau_ref", method="euler", namespace=ns)
    ts = b2.NeuronGroup(params.n_ts, eqs, threshold="v > Vth", reset="v = Vreset", refractory="tau_ref", method="euler", namespace=ns)

    mon_inh = b2.NeuronGroup(1, eqs, threshold="v > Vth", reset="v = Vreset", refractory="tau_ref", method="euler", namespace=ns)
    ts_inh = b2.NeuronGroup(1, eqs, threshold="v > Vth", reset="v = Vreset", refractory="tau_ref", method="euler", namespace=ns)

    mon.v = "El + rand()*2*mV"
    ts.v = "El + rand()*2*mV"
    mon_inh.v = "El"
    ts_inh.v = "El"

    # LL -> MON: random sparse + optional weak-topographic, optionally plastic.
    if not params.ll_mon_use_stdp:
        # Fixed weights (original behavior).
        s_ll_mon = b2.Synapses(ll, mon, "w : volt", on_pre="ge_post += w")
        if params.ll_to_mon_topography_strength <= 0.0:
            s_ll_mon.connect(p=params.p_ll_to_mon)
        else:
            ll_i_topo, mon_j_topo = build_ll_to_mon_indices(
                n_ll=params.n_ll,
                n_mon=params.n_mon,
                in_degree=params.ll_to_mon_in_degree,
                sigma_ll=params.ll_to_mon_sigma,
                topography_strength=params.ll_to_mon_topography_strength,
                seed=params.seed + 31,
            )
            s_ll_mon.connect(i=ll_i_topo, j=mon_j_topo)
        s_ll_mon.w = f"{params.ll_mon_w_mean_mV}*mV + {params.ll_mon_w_jitter_mV}*mV*rand()"
    else:
        # LL->MON with STDP (Hebbian plastic expansion).
        if params.ll_to_mon_topography_strength <= 0.0:
            ll_i_topo = mon_j_topo = None
        else:
            ll_i_topo, mon_j_topo = build_ll_to_mon_indices(
                n_ll=params.n_ll,
                n_mon=params.n_mon,
                in_degree=params.ll_to_mon_in_degree,
                sigma_ll=params.ll_to_mon_sigma,
                topography_strength=params.ll_to_mon_topography_strength,
                seed=params.seed + 31,
            )
        s_ll_mon = b2.Synapses(
            ll,
            mon,
            model="""
            w : volt
            dapre/dt = -apre/taupre : 1 (event-driven)
            dapost/dt = -apost/taupost : 1 (event-driven)
            """,
            on_pre="""
            ge_post += w
            apre += Apre
            w = clip(w + apost*mV, 0*mV, wmax)
            """,
            on_post="""
            apost += Apost
            w = clip(w + apre*mV, 0*mV, wmax)
            """,
            namespace={
                "taupre": 20 * b2.ms,
                "taupost": 20 * b2.ms,
                "Apre": params.ll_mon_apre,
                "Apost": params.ll_mon_apost,
                "wmax": params.ll_mon_wmax_mV * b2.mV,
            },
        )
        if params.ll_to_mon_topography_strength <= 0.0:
            s_ll_mon.connect(p=params.p_ll_to_mon)
        else:
            s_ll_mon.connect(i=ll_i_topo, j=mon_j_topo)
        s_ll_mon.w = f"{params.ll_mon_w_init_mV}*mV + {params.ll_mon_w_jitter_stdp_mV}*mV*rand()"
        # Baseline incoming sum per MON neuron (target for homeostasis).
        w_ll_init_mV = np.array(s_ll_mon.w[:] / b2.mV, dtype=float, copy=True)
        j_ll_conn = np.array(s_ll_mon.j[:], dtype=int, copy=True)
        incoming0 = np.bincount(j_ll_conn, weights=w_ll_init_mV, minlength=params.n_mon)
        ll_mon_homeo_target = float(np.mean(incoming0[incoming0 > 0])) if np.any(incoming0 > 0) else float(
            np.mean(incoming0)
        )
    # MON -> TS: random+weak-topographic, plastic (STDP).
    mon_i, ts_j, _ = build_mon_to_ts_indices(
        n_mon=params.n_mon,
        n_ts=params.n_ts,
        out_degree=params.mon_to_ts_out_degree,
        sigma_ts=params.mon_to_ts_sigma,
        topography_strength=params.mon_to_ts_topography_strength,
        seed=params.seed,
    )

    s_mon_ts = b2.Synapses(
        mon,
        ts,
        model="""
        w : 1
        dapre/dt = -apre/taupre : 1 (event-driven)
        dapost/dt = -apost/taupost : 1 (event-driven)
        """,
        on_pre="""
        ge_post += mon_ts_gain*w*mV
        apre += Apre
        w = clip(w + apost, 0, wmax)
        """,
        on_post="""
        apost += Apost
        w = clip(w + apre, 0, wmax)
        """,
        namespace={
            "taupre": 20 * b2.ms,
            "taupost": 20 * b2.ms,
            "Apre": params.mon_ts_apre,
            "Apost": params.mon_ts_apost,
            "wmax": params.mon_ts_wmax,
            "mon_ts_gain": params.mon_ts_gain_mV,
        },
    )
    s_mon_ts.connect(i=mon_i, j=ts_j)
    s_mon_ts.w = f"{params.mon_ts_w_init} + {params.mon_ts_w_jitter}*rand()"

    # Background noisy drive.
    bg_mon = b2.PoissonGroup(params.n_mon, rates=params.bg_rate_mon_hz * b2.Hz)
    bg_ts = b2.PoissonGroup(params.n_ts, rates=params.bg_rate_ts_hz * b2.Hz)
    s_bg_mon = b2.Synapses(bg_mon, mon, on_pre=f"ge_post += {params.bg_w_mon_mV}*mV")
    s_bg_mon.connect(condition="i == j")
    s_bg_ts = b2.Synapses(bg_ts, ts, on_pre=f"ge_post += {params.bg_w_ts_mV}*mV")
    s_bg_ts.connect(condition="i == j")

    # MON global inhibition.
    s_mon_to_inh = b2.Synapses(mon, mon_inh, on_pre=f"ge_post += {params.mon_to_global_inh_drive_mV}*mV")
    s_mon_to_inh.connect(p=params.mon_to_global_inh_p)
    s_inh_to_mon = b2.Synapses(mon_inh, mon, "w : volt", on_pre="gi_post += w")
    s_inh_to_mon.connect()
    s_inh_to_mon.w = params.global_inh_to_mon_mV * b2.mV

    # TS local lateral inhibition (toroidal: TS 0 and n_ts-1 are neighbors so no edge advantage).
    src, dst, wlat = [], [], []
    radius = params.ts_lateral_radius
    n_ts = params.n_ts
    for ts_src in range(n_ts):
        for ts_dst in range(n_ts):
            if ts_src == ts_dst:
                continue
            ring_dist = abs(ts_src - ts_dst)
            ring_dist = min(ring_dist, n_ts - ring_dist)
            if ring_dist > radius:
                continue
            src.append(ts_src)
            dst.append(ts_dst)
            wlat.append(params.ts_local_inh_peak_mV * (1.0 - ring_dist / radius))

    s_ts_lat = b2.Synapses(ts, ts, "w : volt", on_pre="gi_post += w")
    s_ts_lat.connect(i=np.asarray(src), j=np.asarray(dst))
    wlat_base_mV = np.asarray(wlat, dtype=float)
    s_ts_lat.w = wlat_base_mV * b2.mV

    # Optional TS feedback inhibition (global): TS -> inhibitory cell -> TS.
    if bool(params.use_ts_feedback_inh):
        s_ts_to_inh = b2.Synapses(ts, ts_inh, on_pre=f"ge_post += {params.ts_to_global_inh_drive_mV}*mV")
        s_ts_to_inh.connect(p=float(np.clip(params.ts_to_global_inh_p, 0.0, 1.0)))
        s_inh_to_ts = b2.Synapses(ts_inh, ts, "w : volt", on_pre="gi_post += w")
        s_inh_to_ts.connect()
        s_inh_to_ts.w = float(max(0.0, params.global_inh_to_ts_mV)) * b2.mV

    # Monitors.
    sp_ll = b2.SpikeMonitor(ll)
    sp_mon = b2.SpikeMonitor(mon)
    sp_ts = b2.SpikeMonitor(ts)
    pr_mon = b2.PopulationRateMonitor(mon)
    pr_ts = b2.PopulationRateMonitor(ts)

    # Save fixed LL->MON weights in mV for map metric.
    ll_i = np.array(s_ll_mon.i[:], dtype=int, copy=True)
    ll_j = np.array(s_ll_mon.j[:], dtype=int, copy=True)
    ll_w_mV = np.array(s_ll_mon.w[:] / b2.mV, dtype=float, copy=True)

    # Save MON->TS initial state.
    w_before = np.array(s_mon_ts.w[:], dtype=float, copy=True)

    # Checkpoint records.
    rng = np.random.default_rng(params.seed + 777)
    tracked_n = min(24, w_before.size)
    tracked_idx = rng.choice(w_before.size, size=tracked_n, replace=False)

    checkpoint_t_s = [0.0]
    w_mean_series = [float(np.mean(w_before))]
    w_std_series = [float(np.std(w_before))]
    tracked_weight_series = [w_before[tracked_idx].copy()]
    w_mean_abs_delta_series = [0.0]
    w_frac_delta_gt_1e3_series = [0.0]

    ts_ckpt_rate_series = []
    pv_ckpt_t_s = []
    pv_sigma_theta_series = []
    pv_delta_trial_series = []
    last_ckpt_t = 0.0
    last_ts_spike_count = 0

    # Training loop (single phase, STDP active on LL->MON (optional) and MON->TS).
    for k in range(params.n_training_trials):
        b2.run(params.trial_duration_s * b2.second)

        if (k + 1) % max(1, params.checkpoint_trials) == 0 or (k + 1) == params.n_training_trials:
            wk = np.array(s_mon_ts.w[:], dtype=float, copy=True)
            t_cur = (k + 1) * params.trial_duration_s

            # Checkpoint TS activity during training.
            dt_ckpt = max(1e-9, t_cur - last_ckpt_t)
            new_ts_spikes = sp_ts.num_spikes - last_ts_spike_count
            ts_rate_ckpt_hz = new_ts_spikes / max(1e-9, params.n_ts * dt_ckpt)

            ts_ckpt_rate_series.append(ts_rate_ckpt_hz)

            # PV quality over training: evaluate on the recent training window.
            ckpt_idx = len(ts_ckpt_rate_series)
            if ckpt_idx % max(1, params.pv_eval_every_checkpoints) == 0:
                i0 = int(np.clip(np.floor(last_ckpt_t / params.dt_s), 0, train_x_cm.size - 1))
                i1 = int(np.clip(np.floor(t_cur / params.dt_s), i0 + 1, train_x_cm.size))
                x_win = train_x_cm[i0:i1]
                t_win = np.arange(x_win.size, dtype=float) * params.dt_s

                sp_t = np.asarray(sp_ts.t / b2.second, dtype=float)
                sp_i = np.asarray(sp_ts.i, dtype=int)
                msp = (sp_t >= last_ckpt_t) & (sp_t < t_cur)
                pv_ck = pv_map_quality_from_ts_spikes(
                    ts_spike_t_s=sp_t[msp],
                    ts_spike_i=sp_i[msp],
                    n_ts=params.n_ts,
                    test_t_s=t_win,
                    test_x_cm=x_win,
                    lateral_line_len_cm=float(StimulusParams().lateral_line_length_cm),
                    test_start_s=last_ckpt_t,
                    dt_s=params.dt_s,
                    n_pos_bins=min(100, params.n_ts),
                )
                pv_ckpt_t_s.append(t_cur)
                pv_sigma_theta_series.append(pv_ck["sigma_theta"])
                pv_delta_trial_series.append(pv_ck["delta_trial"])
            last_ckpt_t = t_cur
            last_ts_spike_count = sp_ts.num_spikes

            checkpoint_t_s.append(t_cur)
            w_mean_series.append(float(np.mean(wk)))
            w_std_series.append(float(np.std(wk)))
            tracked_weight_series.append(wk[tracked_idx].copy())
            dwk = np.abs(wk - w_before)
            w_mean_abs_delta_series.append(float(np.mean(dwk)))
            w_frac_delta_gt_1e3_series.append(float(np.mean(dwk > 1e-3)))

        # LL->MON homeostasis (if enabled) every ll_mon_homeo_every_trials.
        if params.ll_mon_use_stdp and params.ll_mon_homeo_eta > 0.0 and (
            (k + 1) % max(1, params.ll_mon_homeo_every_trials) == 0
        ):
            w_ll_arr = np.array(s_ll_mon.w[:] / b2.mV, dtype=float, copy=True)
            j_ll_conn = np.array(s_ll_mon.j[:], dtype=int, copy=True)
            incoming = np.bincount(j_ll_conn, weights=w_ll_arr, minlength=params.n_mon)
            scale = np.ones(params.n_mon, dtype=float)
            nonzero = incoming > 1e-12
            if np.any(nonzero):
                ratio = ll_mon_homeo_target / np.maximum(incoming[nonzero], 1e-12)
                scale[nonzero] = 1.0 + params.ll_mon_homeo_eta * (ratio - 1.0)
                scale = np.clip(scale, 0.9, 1.1)
                w_ll_arr = np.clip(w_ll_arr * scale[j_ll_conn], 0.0, params.ll_mon_wmax_mV)
                s_ll_mon.w = w_ll_arr * b2.mV

    # Freeze STDP for test.
    s_mon_ts.namespace["Apre"] = 0.0
    s_mon_ts.namespace["Apost"] = 0.0

    # Test run.
    b2.run(test_duration_s * b2.second, report="text")

    w_after = np.array(s_mon_ts.w[:], dtype=float, copy=True)
    dw = w_after - w_before
    abs_dw = np.abs(dw)

    pvq = pv_map_quality_from_ts_spikes(
        ts_spike_t_s=np.asarray(sp_ts.t / b2.second, dtype=float),
        ts_spike_i=np.asarray(sp_ts.i, dtype=int),
        n_ts=params.n_ts,
        test_t_s=np.asarray(test_sim["t_s"], dtype=float),
        test_x_cm=np.asarray(test_sim["X_cm"], dtype=float),
        lateral_line_len_cm=float(StimulusParams().lateral_line_length_cm),
        test_start_s=train_duration_s,
        dt_s=params.dt_s,
        n_pos_bins=min(100, params.n_ts),
    )

    stab_t = estimate_stabilization_time(np.asarray(checkpoint_t_s), np.asarray(w_mean_series))

    return {
        "params": params,
        "train_samples": train_samples,
        "train_x_cm": np.asarray(train_x_cm, dtype=float),
        "test_sim": test_sim,
        "sp_ll": sp_ll,
        "sp_mon": sp_mon,
        "sp_ts": sp_ts,
        "pr_mon": pr_mon,
        "pr_ts": pr_ts,
        "w_before": w_before,
        "w_after": w_after,
        "ll_to_mon_i": ll_i,
        "ll_to_mon_j": ll_j,
        "ll_to_mon_w_mV": ll_w_mV,
        "mon_to_ts_i": np.array(s_mon_ts.i[:], dtype=int, copy=True),
        "mon_to_ts_j": np.array(s_mon_ts.j[:], dtype=int, copy=True),
        "checkpoint_t_s": np.asarray(checkpoint_t_s),
        "w_mean_series": np.asarray(w_mean_series),
        "w_std_series": np.asarray(w_std_series),
        "tracked_weight_series": np.asarray(tracked_weight_series),
        "w_mean_abs_delta_series": np.asarray(w_mean_abs_delta_series),
        "w_frac_delta_gt_1e3_series": np.asarray(w_frac_delta_gt_1e3_series),
        "w_mean_abs_delta_final": float(np.mean(abs_dw)),
        "w_frac_delta_gt_1e3_final": float(np.mean(abs_dw > 1e-3)),
        "w_frac_at_wmax_final": float(np.mean(np.isclose(w_after, params.mon_ts_wmax))),
        "w_frac_at_zero_final": float(np.mean(np.isclose(w_after, 0.0))),
        "ts_ckpt_rate_series_hz": np.asarray(ts_ckpt_rate_series),
        "pv_ckpt_t_s": np.asarray(pv_ckpt_t_s),
        "pv_sigma_theta_series": np.asarray(pv_sigma_theta_series),
        "pv_delta_trial_series": np.asarray(pv_delta_trial_series),
        "stabilization_time_s": stab_t,
        "pv_theta_true": pvq["theta_true"],
        "pv_theta_hat": pvq["theta_hat"],
        "pv_delta_theta": pvq["delta_theta"],
        "pv_theta_bins": pvq["theta_bins"],
        "pv_bias_theta": pvq["bias_theta"],
        "pv_sigma_trial_theta": pvq["sigma_trial_theta"],
        "pv_sigma_theta": pvq["sigma_theta"],
        "pv_delta_trial": pvq["delta_trial"],
        "pv_valid_fraction": pvq["valid_fraction"],
        "train_duration_s": train_duration_s,
        "test_duration_s": test_duration_s,
        "total_duration_s": total_duration_s,
    }


def save_learning_artifacts(result: dict, out_dir: Path, tag: str):
    """
    Save learned weights and connectivity so future tests can reuse training.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    base = out_dir / tag
    weights_path = base.with_suffix(".npz")
    params_path = base.with_name(base.name + "_params.json")

    np.savez_compressed(
        weights_path,
        mon_ts_w=result["w_after"],
        mon_ts_i=result["mon_to_ts_i"],
        mon_ts_j=result["mon_to_ts_j"],
        ll_mon_i=result["ll_to_mon_i"],
        ll_mon_j=result["ll_to_mon_j"],
        ll_mon_w_mV=result["ll_to_mon_w_mV"],
    )

    p = result["params"]
    with params_path.open("w", encoding="utf-8") as f:
        json.dump(
            {
                "mode": "ll_thesis",
                "n_ll": p.n_ll,
                "n_mon": p.n_mon,
                "n_ts": p.n_ts,
                "speed_cm_s": p.speed_cm_s,
                "distance_cm": p.distance_cm,
                "direction": p.direction,
                "training_noise_scale_early": p.training_noise_scale_early,
                "training_noise_scale_late": p.training_noise_scale_late,
                "mon_ts_apre": p.mon_ts_apre,
                "mon_ts_apost": p.mon_ts_apost,
                "mon_ts_wmax": p.mon_ts_wmax,
            },
            f,
            indent=2,
        )
    return weights_path, params_path


# ---------------------------------------------------------
# Plotting
# ---------------------------------------------------------
def save_summary_figure(result, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)

    p = result["params"]
    sp_ll = result["sp_ll"]
    sp_mon = result["sp_mon"]
    sp_ts = result["sp_ts"]
    pr_mon = result["pr_mon"]
    pr_ts = result["pr_ts"]

    fig, axes = plt.subplots(4, 2, figsize=(14, 14))
    ax = axes.ravel()

    # Stimulus overview.
    x_line = np.linspace(0.0, 4.0, p.n_ll)
    ax[0].plot(x_line, np.zeros_like(x_line), "k.", ms=2, label="Lateral line")

    tx = np.array([s["X_cm"] for s in result["train_samples"]])
    ty = np.array([s["D_cm"] for s in result["train_samples"]])
    ax[0].scatter(tx, ty, s=7, alpha=0.25, color="tab:blue", label="Training snapshots")

    tsim = result["test_sim"]
    ax[0].plot(tsim["X_cm"], tsim["Y_cm"], color="tab:red", lw=2.0, label="Test (4 cm)")
    ax[0].set_title("Hydrodynamic stimuli")
    ax[0].set_xlabel("x (cm)")
    ax[0].set_ylabel("y (cm)")
    ax[0].grid(alpha=0.3)
    ax[0].legend(fontsize=7)

    t_train = result["train_duration_s"]
    t_end = result["total_duration_s"]

    # LL spikes.
    ax[1].scatter(sp_ll.t / b2.second, sp_ll.i, s=0.3, color="black")
    ax[1].axvline(t_train, color="tab:red", ls="--", lw=1.0)
    ax[1].set_xlim(0, t_end)
    ax[1].set_title("LL spikes")
    ax[1].set_xlabel("time (s)")
    ax[1].set_ylabel("LL index")

    # MON spikes subset.
    mon_subset = min(400, p.n_mon)
    m = sp_mon.i < mon_subset
    ax[2].scatter((sp_mon.t[m] / b2.second), sp_mon.i[m], s=0.3, color="tab:purple")
    ax[2].axvline(t_train, color="tab:red", ls="--", lw=1.0)
    ax[2].set_xlim(0, t_end)
    ax[2].set_title(f"MON spikes (first {mon_subset})")
    ax[2].set_xlabel("time (s)")
    ax[2].set_ylabel("MON index")

    # TS spikes.
    ax[3].scatter(sp_ts.t / b2.second, sp_ts.i, s=0.5, color="tab:green")
    ax[3].axvline(t_train, color="tab:red", ls="--", lw=1.0)
    ax[3].set_xlim(0, t_end)
    ax[3].set_title("TS spikes")
    ax[3].set_xlabel("time (s)")
    ax[3].set_ylabel("TS index")

    # Population rates.
    ax[4].plot(pr_mon.t / b2.second, pr_mon.smooth_rate(width=20 * b2.ms) / b2.Hz, label="MON")
    ax[4].plot(pr_ts.t / b2.second, pr_ts.smooth_rate(width=20 * b2.ms) / b2.Hz, label="TS")
    ax[4].axvline(t_train, color="tab:red", ls="--", lw=1.0)
    ax[4].set_xlim(0, t_end)
    ax[4].set_title("Population rates")
    ax[4].set_xlabel("time (s)")
    ax[4].set_ylabel("rate (Hz)")
    ax[4].legend()
    ax[4].grid(alpha=0.3)

    # MON->TS weight distribution.
    bins = np.linspace(0.0, p.mon_ts_wmax, 40)
    ax[5].hist(result["w_before"], bins=bins, alpha=0.55, label="before")
    ax[5].hist(result["w_after"], bins=bins, alpha=0.55, label="after")
    ax[5].set_title("MON->TS weights")
    ax[5].set_xlabel("weight")
    ax[5].set_ylabel("count")
    ax[5].legend()

    # Weight stabilization curve.
    ct = result["checkpoint_t_s"]
    wm = result["w_mean_series"]
    ws = result["w_std_series"]
    tw = result["tracked_weight_series"]

    ax[6].plot(ct, wm, lw=2.0, color="tab:blue", label="mean(w)")
    ax[6].fill_between(ct, wm - ws, wm + ws, color="tab:blue", alpha=0.2, label="mean±std")
    for k in range(min(8, tw.shape[1])):
        ax[6].plot(ct, tw[:, k], lw=0.8, alpha=0.5, color="tab:orange")
    if result["stabilization_time_s"] is not None:
        ax[6].axvline(result["stabilization_time_s"], color="tab:green", ls="--", lw=1.2, label="stabilized")
    ax[6].set_title("MON->TS stabilization")
    ax[6].set_xlabel("training time (s)")
    ax[6].set_ylabel("weight")
    ax[6].grid(alpha=0.3)
    ax[6].legend(fontsize=8)

    # PV-based map quality over training checkpoints.
    tpv = result["pv_ckpt_t_s"]
    s_th = result["pv_sigma_theta_series"]
    d_tr = result["pv_delta_trial_series"]
    if tpv.size > 0:
        ax[7].plot(tpv, s_th, lw=1.6, color="tab:blue", label="sigma_theta(t)")
        ax[7].plot(tpv, d_tr, lw=1.6, color="tab:orange", label="delta_trial(t)")
    ax[7].set_title(
        "PV over training "
        f"(final sigma_theta={result['pv_sigma_theta']:.3f}, delta_trial={result['pv_delta_trial']:.3f})"
    )
    ax[7].set_xlabel("training time (s)")
    ax[7].set_ylabel("error (rad)")
    ax[7].grid(alpha=0.3)
    ax[7].legend(fontsize=8)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_ts_tuning_figure(result, out_path: Path, n_examples: int = 16):
    """
    Diagnostic: TS tuning curves vs position during the 4 cm test sweep.
    Shows, for a subset of TS neurons, their firing rate as a function of x.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    p = result["params"]
    sp_ts = result["sp_ts"]
    tsim = result["test_sim"]
    t_train = result["train_duration_s"]

    t_test = np.asarray(tsim["t_s"], dtype=float)
    x_test = np.asarray(tsim["X_cm"], dtype=float)

    # Spike times relative to test start (t_train).
    ts_t = np.asarray(sp_ts.t / b2.second, dtype=float)
    ts_i = np.asarray(sp_ts.i, dtype=int)
    mtest = (ts_t >= t_train) & (ts_t <= result["total_duration_s"])
    ts_t = ts_t[mtest] - t_train
    ts_i = ts_i[mtest]

    if ts_t.size == 0:
        return

    # Use the same time grid as test_sim.
    dt = float(max(p.dt_s, 1e-4))
    n_t = t_test.size
    rates = np.zeros((n_t, p.n_ts), dtype=float)
    k = np.floor(ts_t / dt).astype(int)
    valid = (k >= 0) & (k < n_t) & (ts_i >= 0) & (ts_i < p.n_ts)
    if np.any(valid):
        np.add.at(rates, (k[valid], ts_i[valid]), 1.0 / dt)

    # Bin by position along the 4 cm test path.
    n_pos_bins = min(40, n_t)
    x_edges = np.linspace(x_test.min(), x_test.max(), n_pos_bins + 1)
    x_centers = 0.5 * (x_edges[:-1] + x_edges[1:])
    tuning = np.zeros((p.n_ts, n_pos_bins), dtype=float)
    for b in range(n_pos_bins):
        mb = (x_test >= x_edges[b]) & (x_test < x_edges[b + 1])
        if not np.any(mb):
            continue
        tuning[:, b] = rates[mb, :].mean(axis=0)

    # Plot tuning for a subset of TS neurons.
    ts_indices = np.linspace(0, p.n_ts - 1, num=min(n_examples, p.n_ts), dtype=int)
    fig, axes = plt.subplots(len(ts_indices), 1, figsize=(8, 2.0 * len(ts_indices)), sharex=True)
    if len(ts_indices) == 1:
        axes = [axes]
    for ax, j in zip(axes, ts_indices):
        ax.plot(x_centers, tuning[j, :], "-o", ms=3)
        ax.set_ylabel(f"TS {j}")
        ax.grid(alpha=0.3)
    axes[-1].set_xlabel("position x during test (cm)")
    fig.suptitle("TS tuning curves vs x (test sweep)", y=1.02)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_multiseed_summary(results: list[dict], out_path: Path):
    """Save PV map-quality summary across seeds."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sigma_theta = np.array([r["pv_sigma_theta"] for r in results], dtype=float)
    delta_trial = np.array([r["pv_delta_trial"] for r in results], dtype=float)
    x = np.arange(len(results))

    fig, ax = plt.subplots(1, 1, figsize=(9, 5))
    ax.plot(x, sigma_theta, "o-", color="tab:blue", label="sigma_theta (somatotopic error)")
    ax.plot(x, delta_trial, "s-", color="tab:orange", label="delta_trial (trial variability)")
    ax.set_title("PV map quality across seeds (lower is better)")
    ax.set_xlabel("seed run index")
    ax.set_ylabel("error (rad)")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_learning_curves_figure(result: dict, out_path: Path):
    """Dedicated learning curves: MON->TS weights and PV quality over training."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ct = result["checkpoint_t_s"]
    wm = result["w_mean_series"]
    ws = result["w_std_series"]
    tw = result["tracked_weight_series"]
    wmad = result["w_mean_abs_delta_series"]
    tpv = result["pv_ckpt_t_s"]
    s_th = result["pv_sigma_theta_series"]
    d_tr = result["pv_delta_trial_series"]

    fig, ax = plt.subplots(2, 1, figsize=(10, 8), sharex=False)

    ax[0].plot(ct, wm, lw=2.0, color="tab:blue", label="mean(w)")
    ax[0].fill_between(ct, wm - ws, wm + ws, color="tab:blue", alpha=0.2, label="mean±std")
    for k in range(min(12, tw.shape[1])):
        ax[0].plot(ct, tw[:, k], lw=0.8, alpha=0.45, color="tab:orange")
    ax0b = ax[0].twinx()
    ax0b.plot(ct, wmad, lw=1.6, ls="--", color="tab:red", label="mean|w-w0|")
    ax0b.set_ylabel("mean |delta w|", color="tab:red")
    ax0b.tick_params(axis="y", labelcolor="tab:red")
    ax[0].set_title("MON->TS weights over training")
    ax[0].set_xlabel("training time (s)")
    ax[0].set_ylabel("weight")
    ax[0].grid(alpha=0.3)
    ax[0].legend(fontsize=8)

    if tpv.size > 0:
        ax[1].plot(tpv, s_th, lw=1.8, color="tab:blue", label="sigma_theta(t)")
        ax[1].plot(tpv, d_tr, lw=1.8, color="tab:orange", label="delta_trial(t)")
    ax[1].set_title("PV quality over training (lower is better)")
    ax[1].set_xlabel("training time (s)")
    ax[1].set_ylabel("error (rad)")
    ax[1].grid(alpha=0.3)
    ax[1].legend(fontsize=8)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_ll_mon_weights_figure(result: dict, out_path: Path, n_examples: int = 6):
    """
    Visualize LL->MON connectivity for a small set of MON neurons.

    For each selected MON neuron, plot LL index vs LL->MON weight (mV).
    This helps see whether LL->MON learning + topography produces peaked,
    position-selective input profiles.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    ll_i = result["ll_to_mon_i"]
    ll_j = result["ll_to_mon_j"]
    ll_w = result["ll_to_mon_w_mV"]
    p = result["params"]

    n_mon = p.n_mon
    if n_mon <= 0 or ll_i.size == 0:
        return

    # Pick a few MON neurons spread across the array.
    mon_indices = np.linspace(0, n_mon - 1, num=min(n_examples, n_mon), dtype=int)

    fig, axes = plt.subplots(len(mon_indices), 1, figsize=(8, 2.2 * len(mon_indices)), sharex=True)
    if len(mon_indices) == 1:
        axes = [axes]

    for ax, mj in zip(axes, mon_indices):
        m = ll_j == mj
        if not np.any(m):
            ax.set_ylabel(f"MON {mj}")
            ax.set_ylim(0, 1)
            ax.text(0.5, 0.5, "no inputs", ha="center", va="center", transform=ax.transAxes)
            continue
        x = ll_i[m]
        w = ll_w[m]
        ax.stem(x, w, basefmt=" ")
        ax.set_ylabel(f"MON {mj}")
        ax.grid(alpha=0.3)

    axes[-1].set_xlabel("LL index")
    fig.suptitle("LL→MON weights for example MON neurons", y=1.02)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)

def main():
    parser = argparse.ArgumentParser(description="Lateral-line MON/TS STDP model (Brian2).")
    parser.add_argument(
        "--mode",
        type=str,
        default="ll_thesis",
        choices=["ll_thesis", "ll_fast"],
        help="Parameter preset. Default is strict lateral-line thesis mode.",
    )
    parser.add_argument(
        "--save-weights-dir",
        type=str,
        default="SavedModels/ll_thesis_no_noise",
        help="Folder where learned weights/connectivity snapshots are stored.",
    )
    parser.add_argument(
        "--save-tag",
        type=str,
        default="latest",
        help="Filename tag for saved artifacts (without extension).",
    )
    parser.add_argument(
        "--multi-seed",
        type=int,
        default=1,
        help="Number of seeds to run and summarize (1 = single run).",
    )
    parser.add_argument(
        "--seed-start",
        type=int,
        default=123,
        help="Starting seed for multi-seed runs.",
    )
    parser.add_argument(
        "--n-training-trials",
        type=int,
        default=None,
        help="Override number of training trials (default from --mode).",
    )
    parser.add_argument(
        "--distance-cm",
        type=float,
        default=None,
        help="Override test distance Y (cm) used in make_test_rates().",
    )
    parser.add_argument(
        "--training-distance-min-cm",
        type=float,
        default=None,
        help="Override minimum training distance (cm) for snapshot sampling.",
    )
    parser.add_argument(
        "--training-distance-max-cm",
        type=float,
        default=None,
        help="Override maximum training distance (cm) for snapshot sampling.",
    )
    parser.add_argument(
        "--ll-mon-topo",
        type=float,
        default=None,
        help="Override LL->MON weak topography strength.",
    )
    parser.add_argument(
        "--mon-ts-topo",
        type=float,
        default=None,
        help="Override MON->TS weak topography strength.",
    )
    parser.add_argument(
        "--ll-rate-mode",
        type=str,
        choices=["raw", "modulation"],
        default=None,
        help="Use raw LL rates or only modulation above spontaneous baseline.",
    )
    parser.add_argument(
        "--ll-baseline-subtract-hz",
        type=float,
        default=None,
        help="Additional LL baseline subtraction before Poisson drive (Hz).",
    )
    parser.add_argument(
        "--ll-rate-gain",
        type=float,
        default=None,
        help="Multiplicative gain on LL rates before Poisson drive.",
    )
    parser.add_argument(
        "--use-ll-mon-stdp",
        action="store_true",
        help="Enable STDP on LL->MON synapses (plastic expansion layer).",
    )
    parser.add_argument(
        "--ll-mon-apre",
        type=float,
        default=None,
        help="Override LL->MON Apre (pre-synaptic STDP increment).",
    )
    parser.add_argument(
        "--ll-mon-apost",
        type=float,
        default=None,
        help="Override LL->MON Apost (post-synaptic STDP increment).",
    )
    parser.add_argument(
        "--ll-mon-wmax-mv",
        type=float,
        default=None,
        help="Override LL->MON maximal weight (mV).",
    )
    parser.add_argument(
        "--ll-mon-w-init-mv",
        type=float,
        default=None,
        help="Override LL->MON initial mean weight (mV) when STDP is enabled.",
    )
    parser.add_argument(
        "--mon-ts-sigma",
        type=float,
        default=None,
        help="Override MON->TS weak-topography spread (TS index units).",
    )
    parser.add_argument(
        "--mon-ts-out-degree",
        type=int,
        default=None,
        help="Override MON->TS outgoing synapses per MON neuron.",
    )
    parser.add_argument(
        "--ts-lateral-radius",
        type=int,
        default=None,
        help="Override TS local lateral inhibition radius (in TS neuron indices).",
    )
    parser.add_argument(
        "--ts-local-inh-peak-mv",
        type=float,
        default=None,
        help="Override TS local lateral inhibition peak strength (mV).",
    )
    parser.add_argument(
        "--use-ts-feedback-inh",
        action="store_true",
        help="Enable TS activity-dependent feedback inhibition (global TS inhibition).",
    )
    parser.add_argument(
        "--ts-feedback-drive-mv",
        type=float,
        default=None,
        help="Override TS->TS-inh drive strength (mV) when feedback inhibition is enabled.",
    )
    parser.add_argument(
        "--ts-feedback-inh-mv",
        type=float,
        default=None,
        help="Override TS-inh->TS inhibition strength (mV) when feedback inhibition is enabled.",
    )
    parser.add_argument(
        "--ts-feedback-p",
        type=float,
        default=None,
        help="Override TS->TS-inh connection probability (0..1) when feedback inhibition is enabled.",
    )
    parser.add_argument(
        "--mon-global-inh-mv",
        type=float,
        default=None,
        help="Override MON global inhibition strength onto MON (mV).",
    )
    parser.add_argument(
        "--mon-ts-gain-mv",
        type=float,
        default=None,
        help="Override MON->TS EPSP gain (mV per unit weight).",
    )
    parser.add_argument(
        "--bg-rate-mon-hz",
        type=float,
        default=None,
        help="Override MON background Poisson drive rate (Hz).",
    )
    parser.add_argument(
        "--bg-rate-ts-hz",
        type=float,
        default=None,
        help="Override TS background Poisson drive rate (Hz).",
    )
    parser.add_argument(
        "--bg-w-ts-mv",
        type=float,
        default=None,
        help="Override TS background synaptic weight (mV).",
    )
    args = parser.parse_args()

    params = apply_model_mode(NetworkParams(), args.mode)
    override = {"seed": args.seed_start}
    if args.n_training_trials is not None:
        override["n_training_trials"] = max(1, int(args.n_training_trials))
    if args.distance_cm is not None:
        override["distance_cm"] = float(max(1e-6, args.distance_cm))
    if args.training_distance_min_cm is not None:
        override["training_distance_min_cm"] = float(max(0.0, args.training_distance_min_cm))
    if args.training_distance_max_cm is not None:
        override["training_distance_max_cm"] = float(max(0.0, args.training_distance_max_cm))
    if args.ll_mon_topo is not None:
        override["ll_to_mon_topography_strength"] = float(max(0.0, args.ll_mon_topo))
    if args.mon_ts_topo is not None:
        override["mon_to_ts_topography_strength"] = float(max(0.0, args.mon_ts_topo))
    if args.ll_rate_mode is not None:
        override["ll_rate_mode"] = args.ll_rate_mode
    if args.ll_baseline_subtract_hz is not None:
        override["ll_rate_baseline_subtract_hz"] = float(max(0.0, args.ll_baseline_subtract_hz))
    if args.ll_rate_gain is not None:
        override["ll_rate_gain"] = float(max(0.0, args.ll_rate_gain))
    if args.mon_ts_sigma is not None:
        override["mon_to_ts_sigma"] = float(max(1e-6, args.mon_ts_sigma))
    if args.mon_ts_out_degree is not None:
        override["mon_to_ts_out_degree"] = int(max(1, args.mon_ts_out_degree))
    if args.ts_lateral_radius is not None:
        override["ts_lateral_radius"] = int(max(1, args.ts_lateral_radius))
    if args.ts_local_inh_peak_mv is not None:
        override["ts_local_inh_peak_mV"] = float(max(0.0, args.ts_local_inh_peak_mv))
    if args.mon_ts_gain_mv is not None:
        override["mon_ts_gain_mV"] = float(max(0.0, args.mon_ts_gain_mv))
    if args.bg_rate_mon_hz is not None:
        override["bg_rate_mon_hz"] = float(max(0.0, args.bg_rate_mon_hz))
    if args.bg_rate_ts_hz is not None:
        override["bg_rate_ts_hz"] = float(max(0.0, args.bg_rate_ts_hz))
    if args.bg_w_ts_mv is not None:
        override["bg_w_ts_mV"] = float(max(0.0, args.bg_w_ts_mv))
    if bool(args.use_ll_mon_stdp):
        override["ll_mon_use_stdp"] = True
    if args.ll_mon_apre is not None:
        override["ll_mon_apre"] = float(args.ll_mon_apre)
    if args.ll_mon_apost is not None:
        override["ll_mon_apost"] = float(args.ll_mon_apost)
    if args.ll_mon_wmax_mv is not None:
        override["ll_mon_wmax_mV"] = float(max(0.0, args.ll_mon_wmax_mv))
    if args.ll_mon_w_init_mv is not None:
        override["ll_mon_w_init_mV"] = float(max(0.0, args.ll_mon_w_init_mv))
    if bool(args.use_ts_feedback_inh):
        override["use_ts_feedback_inh"] = True
    if args.ts_feedback_drive_mv is not None:
        override["ts_to_global_inh_drive_mV"] = float(max(0.0, args.ts_feedback_drive_mv))
    if args.ts_feedback_inh_mv is not None:
        override["global_inh_to_ts_mV"] = float(max(0.0, args.ts_feedback_inh_mv))
    if args.ts_feedback_p is not None:
        override["ts_to_global_inh_p"] = float(np.clip(args.ts_feedback_p, 0.0, 1.0))
    if args.mon_global_inh_mv is not None:
        override["global_inh_to_mon_mV"] = float(max(0.0, args.mon_global_inh_mv))
    params = replace(params, **override)

    results = []
    n_runs = max(1, args.multi_seed)
    for k in range(n_runs):
        p_run = replace(params, seed=args.seed_start + k)
        r = run_spatial_two_stage_model(p_run)
        results.append(r)

        output = Path("Picture") / (
            f"brian2_spatial_two_stage_u_{p_run.speed_cm_s:.1f}_nMON_{p_run.n_mon}_nTS_{p_run.n_ts}_seed_{p_run.seed}.png"
        )
        save_summary_figure(r, output)
        curves_out = Path("Picture") / (
            f"brian2_learning_curves_u_{p_run.speed_cm_s:.1f}_nMON_{p_run.n_mon}_nTS_{p_run.n_ts}_seed_{p_run.seed}.png"
        )
        save_learning_curves_figure(r, curves_out)
        llmon_out = Path("Picture") / (
            f"brian2_llmon_weights_u_{p_run.speed_cm_s:.1f}_nMON_{p_run.n_mon}_nTS_{p_run.n_ts}_seed_{p_run.seed}.png"
        )
        save_ll_mon_weights_figure(r, llmon_out)
        ts_tuning_out = Path("Picture") / (
            f"brian2_ts_tuning_u_{p_run.speed_cm_s:.1f}_nMON_{p_run.n_mon}_nTS_{p_run.n_ts}_seed_{p_run.seed}.png"
        )
        save_ts_tuning_figure(r, ts_tuning_out)
        artifacts_dir = Path(args.save_weights_dir)
        weights_path, params_path = save_learning_artifacts(r, artifacts_dir, f"{args.save_tag}_seed_{p_run.seed}")
        print(f"Seed {p_run.seed} saved figure: {output}")
        print(f"Seed {p_run.seed} saved learning curves: {curves_out}")
        print(f"Seed {p_run.seed} saved LL->MON weights figure: {llmon_out}")
        print(f"Seed {p_run.seed} saved weights: {weights_path}")
        print(f"Seed {p_run.seed} saved params: {params_path}")

    result = results[0]
    output = Path("Picture") / f"brian2_spatial_two_stage_u_{params.speed_cm_s:.1f}_nMON_{params.n_mon}_nTS_{params.n_ts}.png"
    save_summary_figure(result, output)
    curves_out = Path("Picture") / f"brian2_learning_curves_u_{params.speed_cm_s:.1f}_nMON_{params.n_mon}_nTS_{params.n_ts}.png"
    save_learning_curves_figure(result, curves_out)
    llmon_out = Path("Picture") / f"brian2_llmon_weights_u_{params.speed_cm_s:.1f}_nMON_{params.n_mon}_nTS_{params.n_ts}.png"
    save_ll_mon_weights_figure(result, llmon_out)
    ts_tuning_out = Path("Picture") / (
        f"brian2_ts_tuning_u_{params.speed_cm_s:.1f}_nMON_{params.n_mon}_nTS_{params.n_ts}.png"
    )
    save_ts_tuning_figure(result, ts_tuning_out)
    if args.mode == "ll_thesis":
        latest_plot = Path("Picture") / "LL_THESIS_BASELINE_ACTIVE_latest.png"
        latest_plot.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(output, latest_plot)
    if n_runs > 1:
        multi_out = Path("Picture") / f"brian2_multiseed_summary_n{n_runs}.png"
        save_multiseed_summary(results, multi_out)
        print(f"Saved multiseed summary: {multi_out}")

    print(f"Mode: {args.mode}")
    print(
        "Config: "
        f"train_trials={params.n_training_trials}, trial_dur={params.trial_duration_s}s, "
        f"MON->TS out_degree={params.mon_to_ts_out_degree}, sigma={params.mon_to_ts_sigma}, "
        f"topo_strength={params.mon_to_ts_topography_strength}, "
        f"MON->TS gain={params.mon_ts_gain_mV}mV, "
        f"MON inh={params.global_inh_to_mon_mV}mV, TS lat peak={params.ts_local_inh_peak_mV}mV, "
        f"TS lat radius={params.ts_lateral_radius}, "
        f"train_noise=({params.training_noise_scale_early}->{params.training_noise_scale_late}), "
        f"ll_rate_mode={params.ll_rate_mode}, ll_baseline_subtract_hz={params.ll_rate_baseline_subtract_hz}, "
        f"ll_rate_gain={params.ll_rate_gain}"
    )
    print(f"Saved: {output}")
    print(f"Saved learning curves: {curves_out}")
    if args.mode == "ll_thesis":
        print(f"Saved latest copy: {Path('Picture') / 'LL_THESIS_BASELINE_ACTIVE_latest.png'}")
    if n_runs == 1:
        print(f"Spikes: LL={result['sp_ll'].num_spikes}, MON={result['sp_mon'].num_spikes}, TS={result['sp_ts'].num_spikes}")
        ts_t_abs = np.asarray(result["sp_ts"].t / b2.second, dtype=float)
        t0 = float(result["train_duration_s"])
        t1 = float(result["train_duration_s"] + result["test_duration_s"])
        n_ts_test = int(np.sum((ts_t_abs >= t0) & (ts_t_abs < t1)))
        print(f"TS spikes during test window: {n_ts_test}")
        n_mon_ts = len(result["mon_to_ts_i"])
        tot_s = result["total_duration_s"]
        mon_rate_per_neuron = result["sp_mon"].num_spikes / max(1, result["params"].n_mon * tot_s)
        print(f"MON->TS synapses: {n_mon_ts}, MON rate per neuron: {mon_rate_per_neuron:.4f} Hz")
        ts_rate = result["pr_ts"].smooth_rate(width=20 * b2.ms) / b2.Hz
        print(f"Max TS population rate (20 ms smooth): {float(np.max(ts_rate)):.2f} Hz")
        print(
            "Weight change: "
            f"mean|dw|={result['w_mean_abs_delta_final']:.6f}, "
            f"frac(|dw|>1e-3)={result['w_frac_delta_gt_1e3_final']:.3f}, "
            f"frac(w==wmax)={result['w_frac_at_wmax_final']:.3f}, "
            f"frac(w==0)={result['w_frac_at_zero_final']:.3f}"
        )
    else:
        sig = np.array([r["pv_sigma_theta"] for r in results], dtype=float)
        dtr = np.array([r["pv_delta_trial"] for r in results], dtype=float)
        print(
            "Multi-seed PV mean±std: "
            f"sigma_theta={float(np.mean(sig)):.4f}±{float(np.std(sig)):.4f}, "
            f"delta_trial={float(np.mean(dtr)):.4f}±{float(np.std(dtr)):.4f}"
        )
    if result["stabilization_time_s"] is None:
        print("Estimated stabilization time: not reached")
    else:
        print(f"Estimated stabilization time: {result['stabilization_time_s']:.2f} s")
    print(
        "PV map quality: "
        f"sigma_theta={result['pv_sigma_theta']:.4f} rad, "
        f"delta_trial={result['pv_delta_trial']:.4f} rad, "
        f"valid_fraction={result['pv_valid_fraction']:.3f}"
    )


if __name__ == "__main__":
    main()
