#!/usr/bin/env python3
"""
tools/update_simulations_index.py
---------------------------------
Scan Runs/ and regenerate the auto-generated block of SIMULATIONS_INDEX.md.

Triggered by the project Stop hook in .claude/settings.json.

Only the content between
    <!-- AUTOGEN:START -->
    <!-- AUTOGEN:END -->
is rewritten. The curated narrative above the markers is preserved untouched.
If markers are missing, the block is appended.

Run manually:
    python tools/update_simulations_index.py
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = ROOT / "Runs"
INDEX_FILE = ROOT / "SIMULATIONS_INDEX.md"

MARK_START = "<!-- AUTOGEN:START -->"
MARK_END   = "<!-- AUTOGEN:END -->"


# ---------------------------------------------------------------
# Categorise a run directory by name.
# ---------------------------------------------------------------
def classify(name: str) -> str:
    if re.match(r"^distswp_.*_seed\d+_d\d+$", name):
        return "sweep_run"
    if re.match(r"^distswp_.*_seed\d+_extract$", name):
        return "sweep_extract_tmp"
    if re.match(r"^extract_topo\d+_seed_\d+$", name):
        return "extract_single"
    if re.match(r"^llmon_.*_seeds\d+_\d+$", name) or re.match(r"^llmon_.*_seeds\d+_\d{3}$", name):
        return "training"
    if name.startswith("multidist_") or name.startswith("llmon_extract_"):
        return "training"
    if re.match(r"^\d{8}_\d{6}$", name):
        return "historical"
    return "other"


# ---------------------------------------------------------------
# Read seed_NNN_results.json if present; return list of dicts with seed/sigma/valid.
# ---------------------------------------------------------------
def read_seed_results(run_dir: Path) -> list[dict]:
    out = []
    art = run_dir / "artifacts"
    if not art.is_dir():
        return out
    for f in sorted(art.glob("seed_*_results.json")):
        try:
            d = json.loads(f.read_text())
            out.append(d)
        except Exception:
            pass
    return out


# ---------------------------------------------------------------
# Read latest_seed_NNN_params.json (saved on training completion) -> seeds completed.
# ---------------------------------------------------------------
def trained_seeds(run_dir: Path) -> list[int]:
    art = run_dir / "artifacts"
    if not art.is_dir():
        return []
    seeds = []
    for f in art.glob("latest_seed_*.npz"):
        m = re.search(r"latest_seed_(\d+)\.npz$", f.name)
        if m:
            seeds.append(int(m.group(1)))
    return sorted(seeds)


# ---------------------------------------------------------------
# Build summary tables.
# ---------------------------------------------------------------
def build_block() -> str:
    if not RUNS_DIR.is_dir():
        return f"_Runs/ directory not found at {RUNS_DIR}_\n"

    runs = sorted([p for p in RUNS_DIR.iterdir() if p.is_dir()])
    cats: dict[str, list[Path]] = defaultdict(list)
    for p in runs:
        cats[classify(p.name)].append(p)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append(MARK_START)
    lines.append("")
    lines.append("## 7. Auto-generated run inventory")
    lines.append("")
    lines.append(f"_Regenerated by `tools/update_simulations_index.py` on **{now}**._")
    lines.append(f"_Total run dirs: **{len(runs)}**  ·  Training: {len(cats.get('training', []))}  ·  Sweep runs: {len(cats.get('sweep_run', []))}  ·  Extract: {len(cats.get('extract_single', []))}  ·  Historical: {len(cats.get('historical', []))}_")
    lines.append("")

    # -- Training runs (current, non-historical) --
    train = cats.get("training", [])
    if train:
        lines.append("### Training runs (latest 25 by mtime)")
        lines.append("")
        lines.append("| run-name | seeds done | mean σ_θ | mean valid | mtime |")
        lines.append("|----------|-----------|----------|-----------|-------|")
        train_sorted = sorted(train, key=lambda p: p.stat().st_mtime, reverse=True)[:25]
        for p in train_sorted:
            seeds = trained_seeds(p)
            results = read_seed_results(p)
            if results:
                sig = [r.get("sigma_theta_rad", float("nan")) for r in results]
                val = [r.get("valid_fraction", float("nan")) for r in results]
                sig_str = f"{sum(sig)/len(sig):.3f}" if sig else "—"
                val_str = f"{sum(val)/len(val):.3f}" if val else "—"
            else:
                sig_str = val_str = "—"
            mt = datetime.fromtimestamp(p.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
            seeds_str = ",".join(str(s) for s in seeds) if seeds else "—"
            lines.append(f"| `{p.name}` | {len(seeds)} ({seeds_str}) | {sig_str} | {val_str} | {mt} |")
        lines.append("")

    # -- Distance-sweep labels (grouped) --
    sweep = cats.get("sweep_run", [])
    if sweep:
        # Group by label = portion of name between "distswp_" and "_seed".
        groups: dict[str, list[Path]] = defaultdict(list)
        for p in sweep:
            m = re.match(r"^distswp_(.+?)_seed\d+_d\d+$", p.name)
            if m:
                groups[m.group(1)].append(p)
        lines.append("### Distance sweeps (by label)")
        lines.append("")
        lines.append("| label | runs done | distinct seeds | distinct distances | latest mtime |")
        lines.append("|-------|-----------|----------------|--------------------|--------------|")
        for label in sorted(groups.keys()):
            paths = groups[label]
            seeds = sorted({int(re.search(r"_seed(\d+)_", p.name).group(1)) for p in paths if re.search(r"_seed(\d+)_", p.name)})
            ds = sorted({int(re.search(r"_d(\d+)$", p.name).group(1)) / 100.0 for p in paths if re.search(r"_d(\d+)$", p.name)})
            mtime = max(p.stat().st_mtime for p in paths)
            mt = datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M")
            ds_str = ", ".join(f"{d:.2f}" for d in ds)
            lines.append(f"| `{label}` | {len(paths)} | {len(seeds)} ({','.join(str(s) for s in seeds)}) | {len(ds)} ({ds_str}) | {mt} |")
        lines.append("")

    # -- Extract single-D runs --
    extract = cats.get("extract_single", [])
    if extract:
        lines.append(f"### Extract single-distance runs: {len(extract)} dirs (see `extract_topoXXX_seed_NNN/`).")
        lines.append("")

    # -- Historical --
    hist = cats.get("historical", []) + cats.get("other", [])
    if hist:
        lines.append(f"### Historical / exploratory: {len(hist)} dirs (see §6 of this index for context).")
        lines.append("")

    lines.append(MARK_END)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------
# Splice new block into INDEX_FILE between markers.
# ---------------------------------------------------------------
def splice(new_block: str) -> bool:
    """Return True if file changed."""
    if not INDEX_FILE.exists():
        # Create a minimal index file with only the auto block.
        INDEX_FILE.write_text(
            "# Simulations Index — LateralLine STDP\n\n"
            "(curated content goes above this marker)\n\n"
            + new_block
        )
        return True
    text = INDEX_FILE.read_text()
    if MARK_START in text and MARK_END in text:
        pattern = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.DOTALL)
        updated = pattern.sub(new_block.rstrip("\n"), text, count=1)
    else:
        # Append a new section at the end.
        if not text.endswith("\n"):
            text += "\n"
        updated = text + "\n" + new_block
    if updated != text:
        INDEX_FILE.write_text(updated)
        return True
    return False


def main() -> int:
    try:
        block = build_block()
        changed = splice(block)
        if changed:
            print(f"[update_simulations_index] updated {INDEX_FILE}", file=sys.stderr)
        else:
            print(f"[update_simulations_index] no changes", file=sys.stderr)
        return 0
    except Exception as e:
        # Don't break the Stop hook — print to stderr and exit 0.
        print(f"[update_simulations_index] ERROR: {e}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
